version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist/consulta-cep"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        - ng build --prod
  post_build:s
   commands:
    - aws cloudfront create-invalidation --distribution-id EG9BMBS9X49LE --paths "/*"
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/consulta-cep*'
    discard-paths: no



